version: '3.4'
services: 
  worker:
    build: .
    image: &img worker 
    command: 
      - celery
      - --app=worker
      - worker
      - --pool=gevent
      - --concurrency=20
      - --loglevel=INFO
      - --events
    environment: &env      
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://guest:guest@rabbitmq:5672
      # - CELERY_RESULT_BACKEND=backend:Backend
      - CELERY_RESULT_PERSISTENT=true
      - CELERY_RESULT_EXCHANGE=results_here_lol
      - CELERY_SEND_EVENTS=true
      - NEWSPAPER_URLS=1,2,3,4,56,7,8,89
      - NEWSPAPER_SCHEDULE=60
    depends_on:
      - beat
      - rabbitmq
    restart: 'no'
    volumes:
      - ./src:/app 

  flower:  
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://guest:guest@rabbitmq:5672
      - CELERY_RESULT_PERSISTENT=true
      - CELERY_RESULT_EXCHANGE=results_here_lol
      - CELERY_SEND_EVENTS=true
      - FLOWER_PORT=5555
    ports:  
      - 5555:5555

  beat:
    build: .
    image: *img
    command: 
      - celery
      - --app=worker
      - beat 
      - --loglevel=INFO
    environment: *env
    depends_on:
      - rabbitmq
    restart: 'no'
    volumes:
      - ./src:/app

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - 4369:4369 
      - 5671:5671 
      - 5672:5672 
      - 15672:15672
    
  
